remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Network Nexus
description: A portfolio site dedicated to showcase the application of advanced algorithms in the domain of computer networks.
