remote_theme:  mmistakes/minimal-mistakes@4.26.2
plugins:
- jekyll-remote-theme
- jekyll-include-cache
title: Network Nexus
description: A portfolio site dedicated to showcase the application of advanced algorithms in the domain of computer networks.
