remote_theme: rundocs/jekyll-rtd-theme
plugins:
- jekyll-remote-theme
title: Network Nexus
description: A portfolio site dedicated to showcase the application of advanced algorithms in the domain of computer networks.
